export const COMPANY_NAME = "Robbkontrol"
export const SITE_NAME = "Dashboard"
export const SITE_DESCRIPTION = "Robbkontrol Kft. admin dashboard"
export const SITE_URL = "https://dashboard.robbkontrolkft.hu"
export const SITE_LOCALE = "hu_HU"
export const SUPPORTED_SITE_LOCALES = ["en_US", "hu_HU"]
export const DEFAULT_LOCALE = "hu"
export const SUPPORTED_LOCALES = ["en", "hu"]
export const DEFAULT_PAGINATION_LIMIT = 10
export const MAX_PAGINATION_LIMIT = 100
export const DATE_FORMAT = "yyyy-MM-dd"
export const TIME_FORMAT = "HH:mm"
export const DATETIME_FORMAT = "yyyy-MM-dd HH:mm"
export const DEFAULT_TIMEZONE = "Europe/Budapest"
export const ITEMS_PER_PAGE_OPTIONS = [10, 25, 50, 100]
export const DEFAULT_ITEMS_PER_PAGE = 10
export const PHONE_COUNTRY_DEFAULT = "HU" // ISO 3166-1 alpha-2
export const PHONE_COUNTRY_OPTIONS = ["US", "GB", "FR", "DE", "HU"] // ISO 3166-1 alpha-2
